[build]
  base    = "cnwebsite"
  publish = "cnwebsite/build/react-native"
  command = "sed -i -e \"s|const baseUrl .*|const baseUrl = '/';|g\" siteConfig.js && yarn install && node netlify-reduce-versions && yarn build"
